server:
  servlet:
    context-path: /api

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #datasource:
    #url: jdbc:postgresql://localhost:5432/shoppingfy
    #username: postgres
    #password: root
    #hikari:
      #maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: "JAVAS_@1234GHJGJFYUIUJKHKJKUHK"
